name: Search Manga

on:
  issues:
    types: [opened]

jobs:
  build:
    if: ${{ startsWith(github.event.issue.title, '[Search]') }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4.2.0
        with:
          python-version: 3.10.6

      - name: Start Download
        run: |
          pip install -r requirements.txt
          python search.py
        env: 
          GHP_TONGLI: ${{ secrets.GHP_TONGLI }}
          NUMBER: ${{ github.event.issue.number }}
